### ISSUE TITLE
databaseService - Java versie

### ISSUE THREAD

**Issue by DominiqueClaes** [mylene/MicroLearning#40]
In de pom.xml wordt er vermeld dat de code met Java 12 gecompileerd moet worden, maar de Dockerfile bevat referenties naar versies 9 en 8. Valt dit nog onder het 'probeersel' item?

**Comment by mylene** [comment]
Ik heb zelf alles omgebouwd naar 12, behalve (zoals volgens mij in de README staat Docker en Kubernetes gerelateerd spul). Niet probeersel, maar nog niet gedaan (omdat deployen nog niet interessant was :))
